cooplatex/cooplatex/urls.py
from django.conf.urls import url, include
from django.shortcuts import redirect
from django.contrib import admin

urlpatterns = [
    url(r'^$', lambda r: redirect('home/')),
    url(r'^home/', include('login.urls', namespace='login')),
    url(r'^dash/', include('editor.urls', namespace='editor')),
    url(r'^admin/', admin.site.urls),
]

cooplatex/editor/urls.py
"""Url routes for editor app"""
from django.conf.urls import url
from . import views

app_name = 'editor'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signout/', views.sign_out, name='signout'),
    url(r'^(?P<ownerID>[0-9]+)/(?P<projectName>[a-zA-Z][0-9a-zA-Z_]+)/compile/', views.compile_project, name='compile'),
    url(r'^(?P<ownerID>[0-9]+)/(?P<projectName>[a-zA-Z][0-9a-zA-Z_]+)/save/', views.save_project, name='save'),
    url(r'^(?P<ownerID>[0-9]+)/(?P<projectName>[a-zA-Z][0-9a-zA-Z_]+)/delete/', views.delete_project, name='delete'),
    url(r'^(?P<ownerID>[0-9]+)/(?P<projectName>[a-zA-Z][0-9a-zA-Z_]+)/newfile/', views.create_new_file, name='newfile'),
    url(r'^(?P<ownerID>[0-9]+)/(?P<projectName>[a-zA-Z][0-9a-zA-Z_]+)/getpdf/', views.download_pdf, name='download_pdf'),
    url(r'^(?P<ownerID>[0-9]+)/(?P<projectName>[a-zA-Z][0-9a-zA-Z_]+)/uploadFile/', views.upload_file, name='uploadFile'),
    url(r'^(?P<ownerID>[0-9]+)/(?P<projectName>[a-zA-Z][0-9a-zA-Z_]+)/', views.editor_page, name='editorPage'),
    
]

cooplatex/login/urls.py
"""Url routes for login app"""
from django.conf.urls import url

from . import views
app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin/', views.sign_in, name='signIn'),
    url(r'^signup/', views.register, name='register'),
    url(r'^verify/(?P<userID>[0-9]+)/(?P<verifyToken>[\w]{32})', views.verifyUser, name='verifyUser'),
    url(r'^pleaseverify/', views.pleaseVerify, name='pleaseVerify'),
]

cooplatex/editor/forms.py
""" Forms for edito app """
from django import forms
from django.core.validators import RegexValidator

VALIDATOR = RegexValidator(r'^[a-zA-Z][0-9a-zA-Z_]+$',
    'Must start with a letter and can only contain alphanumeric characters and undeerscores.')

class ProjectCreateForm(forms.Form):
    """Form for project creation"""
    project_name = forms.CharField(widget=forms.TextInput({
      'required': True,
      'id': 'project-name-input',
      'class': 'form-control',
      'placeholder': 'Title'
    }), max_length=25, min_length=3, validators=[VALIDATOR])

class FileUploadForm(forms.Form):
    file_source = forms.FileField()

cooplatex/editor/views.py
"""Editor app views"""
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponse, HttpResponseForbidden, HttpResponseNotFound

from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.utils import timezone
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseForbidden, HttpResponse
from .forms import ProjectCreateForm, FileUploadForm
from .models import Project
from .s3store import create_empty_file, get_file, save_file, get_pdf
from .compiler import compile_1_tex_file
from .s3store import create_empty_file, create_actual_empty_file
import json
import string

@login_required(login_url='/home/signin/')
def index(request):
    """GET dashboard"""
    # TODO: load available files
    projects = request.user.get_my_projects()
    shared_projects = request.user.get_shared_with_me()
    has_project = projects.count() > 0 or shared_projects.count() > 0

    context = {
        'form': ProjectCreateForm(),
        'has_project': has_project,
        'my_projects': projects,
        'shared_projects': shared_projects,
    }

    if request.method == "GET":
        return render(request, 'editor/index.html', context)
    elif request.method == "POST":
        return create_project(request, context)

@login_required(login_url='/home/signin/')
def sign_out(request):
    """Sign out user"""
    logout(request)
    return redirect('/home')

def create_project(request, context):
    """ creates a project """
    form = ProjectCreateForm(request.POST)

    if not form.is_valid():
        context["error_message"] = "Project name is invalid"
        return render(request, 'editor/index.html', context)
    
    project_name = form.cleaned_data['project_name']

    if Project.objects.filter(owner=request.user, name=project_name).exists():
        context["error_message"] = "You already have a project with that name!"
        return render(request, 'editor/index.html', context)

    try:
        request.user.create_project(project_name)        
    except ValueError:
        context["error_message"] = "Project name is invalid"
        return render(request, 'editor/index.html', context)
    try:
        project = Project.objects.get(owner=request.user, name=project_name)
        # Create file here
        resp = create_empty_file(project.main_file, project_name, request.user.name)
    except Exception as e:
        print(e)
        context["error_message"] = "Project creation failed"
        return render(request, 'editor/index.html', context)

    # Should go to editor view
    context["success_message"] = "Project created"
    return HttpResponseRedirect('/dash')

def create_new_file(request, ownerID, projectName): 
    """creates a new file within a project"""
    if request.method == 'POST':
        newFileName = request.POST.get('filename')
        if request.user.is_authenticated and newFileName != None:
            try:
                try: 
                    p = Project.objects.get(owner=request.user.id, name=projectName)
                except Project.DoesNotExist:
                    return HttpResponseNotFound()
                p.create_new_file(newFileName)
                url = "{}-{}-{}".format(ownerID, projectName, newFileName)
                response = create_actual_empty_file(url)
                if response != None:
                    json_return_ok = {}
                    json_return_ok["ok"] = "file created successfully"
                    json_return_ok["status"] = 200
                    json_return_ok["newfilename"] = newFileName
                    return HttpResponse(status=200, content=json.dumps(json_return_ok), content_type='application/json')
            except ValueError:
                error = {"error": "Invalid filename"}
                return HttpResponse(status=422, content=json.dumps(error), content_type='application/json')
    error = {"error": "did not save successfully"}
    return HttpResponse(status=400, content=json.dumps(error), content_type='application/json')

@login_required(login_url='/home/signin/')
def editor_page(request, ownerID, projectName):
    if request.method == 'GET':
        context={}
        try:
            if request.user.is_authenticated:
                # look up dajngo reques.user and how to authenticate
                p = Project.objects.get(name=projectName, owner=request.user.id)
                files = p.get_files()
                main_fileKey = p.main_file
                mainFileObj = {
                    'body': "",
                    'name': "",
                    'name_id': "",
                }
                editable = []
                other = []
                for f in files:
                    if f.file_type == "tex" or f.file_type == "bib":
                        if f.url == main_fileKey:
                            mainFileObj['name'] = f.file_name
                            mainFileObj['name_id'] = f.file_name.replace( ".", "")
                            mainFileObj['body'] = get_file(f.url)
                        else:
                            tempobj ={}
                            tempobj['name'] = f.file_name
                            tempobj['name_id'] = f.file_name.replace( ".", "")
                            tempobj['body'] = get_file(f.url)
                            editable.append(tempobj)
                    else:
                        other.append({'name': f.file_name, 'url':f.url, 'name_id':f.file_name.replace( ".", "")})
                
            context = {
                'owner': ownerID,
                'projectName': projectName,
                'mainfile': mainFileObj,
                'editable_files': editable,
                "images": other,
            }
    
                # Needs to create a dictionary of all text bodies which will be passed through context
        except Exception as e:
            print(e)
            return HttpResponseForbidden()
        
        return render(request, 'editor/editorpage.html', context)

def save_project(request, ownerID, projectName):
    # need to save the currently opened project
    if request.method == 'POST':
        data = request.POST.get('content')
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)
        filesNotSaved = []
        print("HEREEE")
        if request.user.is_authenticated and body != None:
            try:
                print("HEREEE")
                project = Project.objects.get(owner=request.user.id, name=projectName)
                print("HEREEE")
                for key, value in body.items():
                    if value['name'] != None:
                        try:
                            f = project.get_file(value['name'])
                            save_file(f.url, value['body'])
                        except Exception as e:
                            filesNotSaved.append(value['name'])
                project.date_modified = timezone.now()
                project.save()
                return HttpResponse(status=200, content=json.dumps({'NotSaved': filesNotSaved }), content_type='application/json')
            except Exception as e:
                print(e)
                return HttpResponseNotFound()
            
        return HttpResponse(status=400, content=json.dumps({}), content_type='application/json')   
    
    error = {"error": "did not save successfully"}
    return HttpResponse(status=400, content=json.dumps(error), content_type='application/json')

def compile_project(request, ownerID, projectName):
    if request.method == 'POST':
        if request.user.is_authenticated:
            success, fileKey = compile_1_tex_file(ownerID, projectName)
            if not success:
                error = {"error": "did not compile successfully"}
                return HttpResponse(status=400, content=json.dumps(error), content_type='application/json')
            url = get_pdf(fileKey)
            if url != None:
                json_return_ok = {}
                json_return_ok["link"] = url
                json_return_ok["error_message"] = "Unable to display content"
                json_return_ok["status"] = 200
                return HttpResponse(status=200, content=json.dumps(json_return_ok), content_type='application/json')

    error = {"error": "did not compile successfully"}
    return HttpResponse(status=400, content=json.dumps(error), content_type='application/json')

def delete_project(request, ownerID, projectName):
    """delete project"""
    if request.method == 'POST':
        if request.user.is_authenticated:
            try:
                p = Project.objects.get(owner= request.user.id, name=projectName)
                p.delete()
                deletedproject = "{}-{}".format(ownerID, projectName)
                responseDict = {"projectDeleted":deletedproject}
                return HttpResponse(status=200, content=json.dumps(responseDict), content_type='application/json')
            except Project.DoesNotExist:
                return HttpResponseNotFound()

        return HttpResponseForbidden()

    return HttpResponseBadRequest()


@login_required(login_url='/home/signin/')
def download_pdf(request, ownerID, projectName):
    if request.method == 'POST':
        if request.user.is_authenticated:
            try:
                p = Project.objects.get(owner= request.user.id, name=projectName)
                if p.compiled ==  0:
                    json_return_not_compiled = {'Error': 'The project has not been compiled yet', 'Link': '', 'status': 404}
                    return HttpResponse(status=404, content=json.dumps(json_return_not_compiled), content_type='application/json')
                
                pdf = get_pdf(p.compiled_file)
                json_return_not_compiled = {'Error': '', 'Link': pdf, 'status':200}

cooplatex/editor/templates/editor/editorpage.html
{% load static %}
<html>
    <head>
        <title>CoopLaTeX: Online LaTeX editor!</title>
        <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/octicons.min.css' %}" media="screen" title="no title"/>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">    
        <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script type="text/javascript" src="{% static 'js/editor-splitter.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.4.1/jquery.jgrowl.min.css" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.4.1/jquery.jgrowl.min.js"></script>
        <style type="text/css" media="screen">
            #editor { 
                position: absolute;
                top: 0;
                right: 0;
                bottom: 0;
                left: 0;
            }
        </style>
    </head>
    <body>           
        <nav class="navbar navbar-light bg-light fixed-top">
            <a class="navbar-brand" href="{% url 'login:index' %}">
                <span class="coopLatex">
                    CoopLaTex
                </span>
            </a>

            <div class="mr-auto">
                <span class="navbar-text">
                    {{projectName}}
                </span>
            </div>

            <div class="ml-auto">
                <a class="inline-navlink" href="#">Invite</a>
                <span class="dropdown">
                    <a class="inline-navlink dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Settings</a>
                        <a class="dropdown-item" href="{% url 'editor:signout' %}">Sign Out</a>
                    </div>
                </span>
            </div>
        </nav>
        <nav class="navbar navbar-editing navbar-fixed-top">
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group" role="group" aria-albel="Upload download">
                    <button type="button" class="btn" data-toggle="modal" data-target="#newFileModal">New file</button>
                    <button type="button" class="btn" data-toggle="modal" data-target="#fileUploadModel">Upload file</button>
                    <button type="button" onclick="unimplmented()" class="btn">Download source</button>
                    <button type="button" onclick="downloadPdf()" class="btn">Download pdf</button>
                    <button type="button" onclick="saveSource()" class="btn" id="saveSource">Save source</button>
                </div>
            </div>
            <div class="btn-group" role="group" aria-albel="Undo redo">
                <button type="button" onclick="unimplmented()" class="btn">Undo</button>
                <button type="button" onclick="unimplmented()" class="btn">Redo</button>
            </div>
            <button type="button" onclick="unimplmented()" class="btn">Comment selection</button>
            <div class="btn-group" role="group" aria-albel="Upload download">
                <button type="button" onclick="compile()" class="btn" id="compile">Compile</button>          
                <button type="button" onclick="unimplmented()" class="btn">Logs/output files</button>
            </div>                 
        </nav>
        <div id="container1" class="panel-container">
            <div id="sidebar" class="panel-file-view">                
                <ul class="list-group" id="files">
                    <li id="{{mainfile.name_id}}" class="currentfile list-group-item" onclick='toggleFiles("{{mainfile.name_id}}")'>{{mainfile.name}}</li><span style="display:none" id="{{mainfile.name_id}}-body" name="{{mainfile.name}}">{{mainfile.body}}</span>
                    {% for f in editable_files %}
                        <li id="{{f.name_id}}" class="unselectedfile list-group-item" onclick='toggleFiles("{{f.name_id}}")'>{{f.name}}</li><span style="display:none" name="{{f.name}}" id="{{f.name_id}}-body">{{f.body}}</span>
                    {% endfor %}
                    {% for f in images %}
                        <li id="{{f.name_id}}-other" class="unselectedfile list-group-item" onclick='toggleOtherFiles("{{f.name_id}}")'>{{f.name}}</li>
                    {% endfor %}
                </ul>
            </div>            
            <div class="splitter-files"></div>
            <div id="resizable" class="panel-left">
                <pre><div id="editor">{{mainfile.body}}</div></pre>   
            </div>            
            <div id="container2" class="panel-right">
                Press compile to view pdf!
            </div>
        </div>  

        <script src="{% static 'ace-builds-master/src-min-noconflict/ace.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'ace-builds-master/src-min-noconflict/ext-language_tools.js' %}" type="text/javascript" charset="utf-8"></script>
        <script>
            ace.require("ace/ext/language_tools");
            var editor = ace.edit("editor");
            editor.setTheme("ace/theme/chrome");
            editor.getSession().setMode("ace/mode/tex");
            editor.setOptions({
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true,
                wrapBehavioursEnabled: true
            });
            editor.$blockScrolling = Infinity 
            document.getElementById('editor').style.fontSize='12px';
            $( function() {
                $( "#resizable" ).resizable({
                    minHeight: $("#container1").height(),
                    maxHeight: $("#container1").height(),
                    stop: function (event, ui) {editor.resize();}
                });
            });

        </script>
        
        <div class="modal" id="newFileModal" tabindex="-1" role="dialog" aria-labelledby="newFileModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Name your new tex or bib file</h5>
                        <button type="button" class="close" data-dismiss="modal" id="modal-close-button" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="newFileError" style="display: none">
                            <div class="alert alert-danger show" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                Invalid filename
                            </div>
                        </div>
                        <form
                        class="form-inline"
                        method="post" id ="new-file-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class= "col-sm-3">
                                <label for="file-name-input" class="form-control-label">Filename: </label>
                            </div>
                            <!--{{newFileForm.file_name}}-->
                            <div class="col-sm-9">
                                <input id="file-name-input" class="form-control mb-2 mr-sm-2 mb-sm-0" type="text" name="file-name-input">
                            </div>
                        </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" form="new-file-form" class="btn btn-primary">Create new file</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal" id="fileUploadModel" tabindex="-1" role="dialog" aria-labelledby="fileUploadModellabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" >Upload a file</h5>
                            <button type="button" class="close" data-dismiss="modal" id="modal-close-button" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div id="uploadFileError" style="display: none">
                                <div class="alert alert-danger show" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    <span id="uploadErrorMessage">Unkown error occurred</span>
                                </div>
                            </div>
                            <form id="UploadForm">
                                    <label for="id_file_source">File source:</label><input type="file" name="file_source" required="" id="id_file_source">
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <button type="submit" onclick="uploadFile()" class="btn btn-primary">Upload file</button>
                        </div>
                    </div>
                </div>
            </div>

    </body>
</html>

cooplatex/editor/templates/editor/index.html
{% load static %}
<html>
  <head>
    <title>CoopLaTeX: Online LaTeX editor!</title>
    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/octicons.min.css' %}" media="screen" title="no title"/>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dash.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'login:index' %}">
        <span class="coopLatex">
          CoopLaTeX
        </span>
      </a>

      <div class="align-items-end">
        <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="{% url 'editor:signout' %}">Sign Out</a>
            </div>
        </div>
      </div>
    </nav>
    {%if error_message %}
    <div class="alert alert-danger fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{error_message}}
    </div>
    {% endif %}

    {%if success_message %}
    <div class="alert alert-success fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{success_message}}
    </div>
    {% endif %}
    <div class="container-fluid">
        {% if not has_project %}
        <div class="card text-center">
            <div class="no-projects-card">
                <div class="card-block">
                    <h4 class="card-title">You have no projects.</h4>
                    <p class="card-text">To get started press the button below to create yout first project.</p>
                    <a href="#" class="btn btn-success" data-toggle="modal" data-target="#titleModal">Create project</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% if has_project %}
        <div class="row justify-content-between project-bar">
            <div class="col-sm-6"></div>
            <div class="maright-10">
            <div class="col-sm-2 text-right">
                
                <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#titleModal">
                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" viewBox="0 0 12 16"><path fill-rule="evenodd" d="M12 9H7v5H5V9H0V7h5V2h2v5h5z"/></svg>
                </button>
            </div>
            </div>
        </div>
        {% endif %}
        {% if my_projects|length > 0 %}
        <h3>Your Projects</h3>
        <div class="cotainer table-box">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Owner</th>
                        <th>Modified</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in my_projects %}
                    <tr>
                        <td><a href="{{project.owner.id}}/{{project.name}}">{{ project.name }}</a></td>
                        <td>YOU</td>
                        <td>{{ project.date_modified }}</td>
                        <td> 
                            <div class="dropdown">
                                <a class="" href="#" id="itemDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">       
                                    <svg xmlns="http://www.w3.org/2000/svg" width="3" height="16" viewBox="0 0 3 16"><path fill-rule="evenodd" d="M0 2.5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0zm0 5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0zm0 5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0z"/></svg> 
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="itemDropdownMenuLink">
                                        <a class="dropdown-item" href="#">Rename</a>
                                        <a class="dropdown-item" onclick='deleteProject({{project.owner.id}}, "{{project.name}}")' href="#">Delete</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
        {% if shared_projects|length > 0 %}
        <h3>Shared With You</h3>
        <div class="cotainer table-box">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Owner</th>
                        <th>Modified</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in shared_projects %}
                    <tr>
                        <td><a href="#">{{ project.name }}</a></td>
                        <td>{{ project.owner.name }}</td>
                        <td>{{ project.date_modified }}</td>
                        <td> 
                            <div class="dropdown">
                                <a class="" href="#" id="itemDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">       
                                    <svg xmlns="http://www.w3.org/2000/svg" width="3" height="16" viewBox="0 0 3 16"><path fill-rule="evenodd" d="M0 2.5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0zm0 5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0zm0 5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0z"/></svg> 
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="itemDropdownMenuLink">
                                        <a class="dropdown-item" href="#">Leave project</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>


    <div class="modal fade" id="titleModal" tabindex="-1" role="dialog" aria-labelledby="titleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Give a title to your project</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form
                action="{% url 'editor:index' %}"
                method="post" id ="create_form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="project-name-input" class="form-control-label">Title:</label>
                    {{form.project_name}}
                </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="submit"  form="create_form" class="btn btn-primary">Create project</button>
            </div>
            </div>
        </div>
    </div>
  </body>
</html>