cooplatex/cooplatex/urls.py
from django.conf.urls import url, include
from django.shortcuts import redirect
from django.contrib import admin

urlpatterns = [
    url(r'^$', lambda r: redirect('home/')),
    url(r'^home/', include('login.urls', namespace='login')),
    url(r'^dash/', include('editor.urls', namespace='editor')),
    url(r'^admin/', admin.site.urls),
]

cooplatex/login/urls.py
"""Url routes for login app"""
from django.conf.urls import url

from . import views
app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin/', views.sign_in, name='signIn'),
    url(r'^signup/', views.register, name='register'),
    url(r'^verify/(?P<userID>[0-9]+)/(?P<verifyToken>[\w]{32})', views.verifyUser, name='verifyUser'),
    url(r'^pleaseverify/', views.pleaseVerify, name='pleaseVerify'),
]

cooplatex/login/models.py
"""Models for login app"""
import re
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from editor.models import Project, Collaborations
from .managers import UserManager

# Create your models here.

class CustomUser(AbstractBaseUser, PermissionsMixin):
    """Custom user class"""
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=30, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)
    verified = models.BooleanField(default=False)
    verify_token = models.CharField(max_length=40)
    objects = UserManager()
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def create_project(self, project_name):
        """ creates a project.
        May raise Value error if project_name is invalid, it may raise
        IntegrityError if project/owner already exist"""
        # TODO: probably create the main file automaticaly
        # TODO: remove 3 character minimum limit on project name (also in corresponding form)
        # First check that project name is valid
        if (re.match(r'^[a-zA-Z][0-9a-zA-Z_]+$', project_name) is not None and len(project_name) > 3 
            and len(project_name) <= 25):
            if Project.objects.filter(owner=self, name=project_name).exists():
                raise ValueError

            Project(name=project_name, owner=self, main_file="{}-{}-main.tex".format(self.id, project_name)).save()
            return

        raise ValueError

    def get_my_projects(self):
        """ Gets projects owned by this user """
        return Project.objects.filter(owner=self)

    def get_shared_with_me(self):
        """ Gets projects id I collaborate in """
        return Collaborations.objects.filter(
            collaborator=self).values_list('project', flat=True)

    def verify(self, token):
        """Verify user"""
        if self.verify_token == token:
            self.verified = True
            self.save()
            return True
        return False

cooplatex/login/forms.py
""" Forms for the login app"""
from django import forms

class RegisterForm(forms.Form):
    """ Register form"""
    name = forms.CharField(widget=forms.TextInput({
      'required': True,
      'id': 'inputName',
      'class': 'form-control',
      'placeholder': 'Name'
    }),
    min_length=3, max_length=20)

    email = forms.EmailField(widget=forms.EmailInput(attrs={
      'required': True,
      'id': 'inputEmail',
      'class': 'form-control',
      'placeholder': 'Email'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
      'required': True,
      'class': 'form-control',
      'id': 'inputPassword',
      'placeholder': 'Password'
    }), min_length=8)

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
      'required': True,
      'class': 'form-control',
      'id': 'inputPassword1',
      'placeholder': 'Retype Password'
    }), min_length=8)

class SignInForm(forms.Form):
  email = forms.EmailField(widget=forms.EmailInput(attrs={
      'required': True,
      'id': 'inputEmail',
      'class': 'form-control',
      'placeholder': 'Email'
  }))

  password = forms.CharField(widget=forms.PasswordInput(attrs={
      'required': True,
      'class': 'form-control',
      'id': 'inputPassword',
      'placeholder': 'Password'
    }))

cooplatex/login/views.py
"""login app views"""

from django.shortcuts import render, redirect
from .forms import RegisterForm, SignInForm
from .models import CustomUser
from django.utils.crypto import get_random_string
from django.contrib.auth import authenticate, login
from django.core.mail import send_mail
from django.http import HttpResponseNotFound
from .forms import RegisterForm, SignInForm
from .models import CustomUser
import os

def index(request):
    """GET homepage"""
    # Check if there is a session
    if request.user.is_authenticated:
        return redirect("/dash/")
    return render(request, 'login/index.html')

def sign_in(request):
    """GET AND POST sign_in handler"""
    if request.method == 'GET':
        form = SignInForm()
        return render(request, 'login/signin.html',{'form': form})
    else:
        return login_handler(request)

def login_handler(request):
    """login POST handler"""

    form = SignInForm(request.POST)
    error_message = 'Unknown error occured. Please try later.'

    if form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(request, username=email, password=password) 
        if user is not None:
            # TODO: user verified check here
            if user.verified:
                login(request, user)
                request.session["user"] = email
                return redirect("/dash/")
            return redirect('/home/pleaseverify/')
        error_message = 'Invalid login!'

    return render(request, 'login/signin.html', {'form': form, 'error_message':error_message})

def register(request):
    """GET AND POST register handler"""
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'login/register.html', {'form': form, 'done': False})
    else:
        return register_post(request)

def register_post(request):
    """register POST handler"""
    form = RegisterForm(request.POST)
    error_message = 'Check that the fields are valid'

    if form.is_valid():
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        password1 = form.cleaned_data['password1']

        if not password1 == password:
            error_message = "Password does not match"
            return render(request, 'login/register.html', {'form': form,
                'error_message': error_message})

        if len(password) < 8:
            error_message = "Password must be at least 8 characters long"
            return render(request, 'login/register.html',
                 {'form': form, 
                'error_message': error_message})

        if CustomUser.objects.filter(email=email).exists():
            error_message = "Email already in use"
            return render(request, 'login/register.html',
                {'form': form, 
                'error_message': error_message})

        return make_user(name, email, password, request)

    return render(request, 'login/register.html',
         {'form': form, 
        'error_message': error_message})

def make_user(name, email, password, request):
    """Creates a new user"""
    verify_token = get_random_string(length=32)
    user = CustomUser.objects.create_user(email, password)
    user.verify_token = verify_token
    user.name = name
    user.save()
    # sendEmail(user)
    # TODO: don't hard code url
    send_mail(
        'CoopLaTeX: verification email',
        'Here is your verification link: {}/home/verify/{}/{}'.format(os.environ['ROOTHOST'],user.id, user.verify_token),
        'cooplatex@outlook.com',
        [email],
        
    )
    return redirect('/home/pleaseverify/')

def verifyUser(request, userID, verifyToken):
    if request.method == 'GET':
        try:
            user = CustomUser.objects.get(id=userID)
        except CustomUser.DoesNotExist:
            return HttpResponseNotFound('<h1>404<h1>')

        if user.verify(verifyToken):
            return render(request, 'login/success.html')
    return HttpResponseNotFound('<h1>Invalid verification link<h1>')

def pleaseVerify(request):
    print('HELLO1')
    if request.method == 'GET':   
        print('HELLO')
        return render(request, 'login/pleaseverify.html')
    return HttpResponseNotFound()

cooplatex/login/templates/login/index.html
{% load static %}
<html>
  <head>
    <title>CoopLaTeX: Online LaTeX editor!</title>
    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'login:index' %}">
        <span class="coopLatex">
          CoopLaTeX
        </span>
      </a>

      <div class="align-items-end">
          <a href="{% url 'login:signIn' %}">
            <button type="button" class="btn btn-primary btn-sm">Sign In</button>
          </a>
          <a href="{% url 'login:register' %}">
            <button type="button" class="btn btn-outline-secondary btn-sm">Sign Up</button>
          </a>
      </div>
    </nav>
    <div class="jumbotron">
        <h1 class="display-3">Welcome to CoopLaTeX!</h1>
        <p class="lead">CoopLaTeX is a collborative LaTeX editor. Create store and share all your projects, available anywhere! </p>
        <hr class="my-4">
        <p>Get started by singning up.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'login:register' %}" role="button">Sign Up</a>
        </p>
    </div>
  </body>
</html>

cooplatex/login/templates/login/pleaseverify.html
{% load static %}
<html>
    <head>
        <title>CoopLaTeX: Online LaTeX editor!</title>
        <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
        <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
      </head>   

    <body>
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'login:index' %}">
                <span class="coopLatex">
                CoopLaTeX
                </span>
            </a>
            
        </nav>
        <div class= "row h-100">
            <div class="col-md-6 mx-auto my-auto">
                <div class="card card-outline-success mb-3 text-center">
                    <h4 class="card-title">Thank you for signing up</h4>
                    <p> Please verify your email to start using Cooplatex.</p>
                </div>
            </div>
        </div>
    </body>

</html>

cooplatex/login/templates/login/register.html
{% load static %}
<html>
  <head>
    <title>CoopLaTeX: Online LaTeX editor!</title>
    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'login:index' %}">
          <span class="coopLatex">
            CoopLaTeX
          </span>
        </a>
    </nav>
    {% if not done %}
    <div class="container h-100">
      {% if error_message %} 
      <div class="row justify-content-center">
        <span class="form-error">{{error_message}} </span>  
      </div>
      {% endif %}
      <div class="row h-100 justify-content-center">
        <form class="lower-100"
          action="{% url 'login:register' %}"
          method="post">
          {% csrf_token %}
          <div class="form-group row">
              <label for="inputName" class="col-sm-3 col-form-label">
                Name
              </label>
              <div class="col-sm-9">
                {{form.name}}
              </div>
            </div>
          <div class="form-group row">
            <label for="inputEmail" class="col-sm-3 col-form-label">
              Email
            </label>
            <div class="col-sm-9">
              {{form.email}}
            </div>
          </div>
          <div class="form-group row">
            <label for="inputPassword" class="col-sm-3 col-form-label">
              Password
            </label>
            <div class="col-sm-9">
                {{form.password}}
            </div>
          </div>
          <div class="form-group row">
            <label for="inputPassword1" class="col-sm-3 col-form-label">
              Password
            </label>
            <div class="col-sm-9">
                {{form.password1}}
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
    {% endif %}

    {% if done %}
    <div class="container h-100">
      <div class="row justify-content-center">
        THANK YOU FOR REGISTERING VERIFY EMAIL TO CONTINUE :)
      </div>
    </div>
    {% endif %}
  </body>
</html>

cooplatex/login/templates/login/signin.html
{% load static %}


<html>
  <head>
    <title>CoopLaTeX: Online LaTeX editor!</title>
    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'login:index' %}">
          <span class="coopLatex">
            CoopLaTeX
          </span>
        </a>
    </nav>
    <div class="container h-80">
      {% if error_message %} 
      <div class="row justify-content-center">
        <span class="form-error">{{error_message}} </span>  
      </div>
      {% endif %}
      <div class="row h-100 justify-content-center ">
        <form class="lower-100" action="{% url 'login:signIn' %}" method="post">
          {% csrf_token %}
          <div class="form-group row">
            <label for="inputEmail" class="col-sm-3 col-form-label">
              Email
            </label>
            <div class="col-sm-9">
              {{ form.email }}
            </div>
          </div>
          <div class="form-group row">
            <label for="inputPassword" class="col-sm-3 col-form-label">
              Password
            </label>
            <div class="col-sm-9">
              {{ form.password }}
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </body>
</html>

cooplatex/login/templates/login/success.html
{% load static %}
<html>
    <head>
        <title>CoopLaTeX: Online LaTeX editor!</title>
        <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
        <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
      </head>
      

      <body>
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'login:index' %}">
              <span class="coopLatex">
                CoopLaTeX
              </span>
            </a>
      
            
        </nav>
            <div class="d-flex justify-content-center lower-100">
                <div class="alert alert-success" role="alert">
                    <strong>Success! </strong>Click<a href="{% url 'login:signIn' %}" class="alert-link"> here </a>to sign in.
                </div>
            </div>
      </body>

</html>